services:
  app:
    logging:
      driver: awslogs
      options:
        awslogs-region:          "${AWS_REGION}"
        awslogs-group:           "/monitoring-lab/app"
        awslogs-stream:          "node-app"
        awslogs-create-group:    "true"
        awslogs-datetime-format: "%Y-%m-%dT%H:%M:%S"
